### PR TITLE
HTML escape chat message

### PR DESCRIPTION
**Pull request by alanshaw**

### CODE REVIEW

**Comment by nelsonic** [comment]
relates to #25 

> _Question_ is: should we do escaping on the client, server or _both_ and should we store the messages escaped in the "_database_" ?

**Comment by iteles** [comment]
@alanshaw Any idea why travis is upset? :crying_cat_face:

**Comment by nelsonic** [comment]
Given that nothing has been changed in the backend for the tests to be complaining, I'm happy to merge this in and debug it tomorrow evening.

**Comment by nelsonic** [comment]
As expected the build passed once it was merged into master: https://travis-ci.org/dwyl/chat/builds/126452675

**Pull request merged**
